[package]
name = "cava"
version = "0.10.3"
description = "console-based audio visualizer for ALSA, PulseAudio, PipeWire and more"
homepage = "https://github.com/vicvenscob/cava"
license = "MIT"
url = "https://github.com/vicvenscob/cava/archive/refs/heads/master.tar.gz"
depends = []
post_install = "./autogen.sh && ./configure && make && cp cava /usr/local/bin/cava"

[package.files]
